-- MySQL Script generated by MySQL Workbench
-- Wed May 16 08:30:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eventos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eventos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventos` DEFAULT CHARACTER SET utf8 ;
USE `eventos` ;

-- -----------------------------------------------------
-- Table `eventos`.`c_administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`c_administrador` (
  `cod_administrador` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `senha` VARCHAR(50) NULL DEFAULT NULL,
  `ultimo_acesso` DATETIME NULL DEFAULT NULL,
  `super_admin` CHAR(1) NOT NULL DEFAULT 'n',
  `trocar_senha` CHAR(1) NOT NULL DEFAULT 'n',
  `conta_ativa` ENUM('s', 'n') NULL DEFAULT 's',
  PRIMARY KEY (`cod_administrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`c_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`c_endereco` (
  `cod_endereco` INT(11) NOT NULL AUTO_INCREMENT,
  `numero` INT(11) NULL DEFAULT NULL,
  `rua` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` CHAR(2) NULL DEFAULT NULL,
  `pais` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`c_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`c_evento` (
  `cod_evento` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao_evento` VARCHAR(70) NULL DEFAULT NULL,
  `data_realizacao` DATE NULL DEFAULT NULL,
  `cod_endereco` INT(11) NULL DEFAULT NULL,
  `inscricoes_abertas` ENUM('s', 'n') NOT NULL DEFAULT 's',
  `cod_administrador` INT(11) NOT NULL,
  PRIMARY KEY (`cod_evento`),
  INDEX `fk_cevento_cendereco` (`cod_endereco` ASC),
  INDEX `fk_c_evento_c_administrador1_idx` (`cod_administrador` ASC),
  CONSTRAINT `fk_cevento_cendereco`
    FOREIGN KEY (`cod_endereco`)
    REFERENCES `eventos`.`c_endereco` (`cod_endereco`),
  CONSTRAINT `fk_c_evento_c_administrador1`
    FOREIGN KEY (`cod_administrador`)
    REFERENCES `eventos`.`c_administrador` (`cod_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`c_acessos_administrador_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`c_acessos_administrador_evento` (
  `cod_acesso` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_administrador` INT(11) NOT NULL,
  `cod_evento` INT(11) NOT NULL,
  PRIMARY KEY (`cod_acesso`),
  INDEX `fk_acessos_administrador_evento_c_administrador1_idx` (`cod_administrador` ASC),
  INDEX `fk_acessos_administrador_evento_c_evento1_idx` (`cod_evento` ASC),
  CONSTRAINT `fk_acessos_administrador_evento_c_administrador1`
    FOREIGN KEY (`cod_administrador`)
    REFERENCES `eventos`.`c_administrador` (`cod_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acessos_administrador_evento_c_evento1`
    FOREIGN KEY (`cod_evento`)
    REFERENCES `eventos`.`c_evento` (`cod_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`c_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`c_livro` (
  `cod_livro` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_do_livro` INT(11) NOT NULL,
  `numero_de_folhas` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_livro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`c_folha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`c_folha` (
  `cod_folha` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_da_folha` INT(11) NULL DEFAULT NULL,
  `numero_de_registros` INT(11) NULL DEFAULT NULL,
  `cod_livro` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_folha`),
  INDEX `fk_cfolha_clivro` (`cod_livro` ASC),
  CONSTRAINT `fk_cfolha_clivro`
    FOREIGN KEY (`cod_livro`)
    REFERENCES `eventos`.`c_livro` (`cod_livro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`c_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`c_participante` (
  `cod_participante` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_participante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`c_liberacao_certificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`c_liberacao_certificado` (
  `cod_liberacao_certificado` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_registro` INT(11) NULL DEFAULT NULL,
  `numero_folha` INT(11) NULL DEFAULT NULL,
  `numero_livro` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `descricao_evento` VARCHAR(70) NULL DEFAULT NULL,
  `data_realizacao` DATE NULL DEFAULT NULL,
  `data_liberacao` DATE NULL DEFAULT NULL,
  `liberacao_disponivel` ENUM('s', 'n') NULL DEFAULT 's',
  `cod_participante` INT(11) NULL DEFAULT NULL,
  `cod_evento` INT(11) NULL DEFAULT NULL,
  `cod_administrador` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_liberacao_certificado`),
  INDEX `fk_cliberacao_cparticipante` (`cod_participante` ASC),
  INDEX `fk_cliberacao_cevento` (`cod_evento` ASC),
  INDEX `fk_cliberacao_cadministrador` (`cod_administrador` ASC),
  CONSTRAINT `fk_cliberacao_cadministrador`
    FOREIGN KEY (`cod_administrador`)
    REFERENCES `eventos`.`c_administrador` (`cod_administrador`),
  CONSTRAINT `fk_cliberacao_cevento`
    FOREIGN KEY (`cod_evento`)
    REFERENCES `eventos`.`c_evento` (`cod_evento`),
  CONSTRAINT `fk_cliberacao_cparticipante`
    FOREIGN KEY (`cod_participante`)
    REFERENCES `eventos`.`c_participante` (`cod_participante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`c_registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`c_registro` (
  `cod_registro` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_do_registro` INT(11) NULL DEFAULT NULL,
  `cod_evento` INT(11) NULL DEFAULT NULL,
  `cod_participante` INT(11) NULL DEFAULT NULL,
  `cod_folha` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_registro`),
  INDEX `fk_cregistro_cevento` (`cod_evento` ASC),
  INDEX `fk_cregistro_cfolha` (`cod_folha` ASC),
  INDEX `fk_cregistro_cparticipante` (`cod_participante` ASC),
  CONSTRAINT `fk_cregistro_cevento`
    FOREIGN KEY (`cod_evento`)
    REFERENCES `eventos`.`c_evento` (`cod_evento`),
  CONSTRAINT `fk_cregistro_cfolha`
    FOREIGN KEY (`cod_folha`)
    REFERENCES `eventos`.`c_folha` (`cod_folha`),
  CONSTRAINT `fk_cregistro_cparticipante`
    FOREIGN KEY (`cod_participante`)
    REFERENCES `eventos`.`c_participante` (`cod_participante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`c_evento_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`c_evento_log` (
  `cod_log` INT NOT NULL AUTO_INCREMENT,
  `tipo_log` ENUM('i', 'u', 'd') NOT NULL,
  `cod_administrador` INT NULL,
  `nome_administrador` VARCHAR(50) NULL,
  `cod_evento` INT NULL,
  `descricao_evento` VARCHAR(70) NULL,
  `data_log` DATE NULL,
  PRIMARY KEY (`cod_log`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
